services:
  app:
    image: "catwates/stardew-calculator:v1.0.0"
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: local #determines which profiles should activate when the app starts
    ports:
      - "8080:8080" #uses port 8080 on the host machine
    depends_on:
      - postgres #waits for postgres to be ready before starting the app
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stardewcalc
    ports:
      - "5432:5432" #uses port 5432 on the host machine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data #maps directory on host machine to directory in postgres container
#      #the data is persistent even if the container is removed