spring:
  datasource:
    url: jdbc:h2:mem:stardew-calc
  jpa:
    hibernate:
      ddl-auto: update #updates database schema instead of creating a new one
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations:
        - classpath:db/migration
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://postgres:5432/stardewcalc #connects to a postgres database using JDBC driver
    username: postgres
    password: password



