-- https://blog.jetbrains.com/idea/2024/11/how-to-use-flyway-for-database-migrations-in-spring-boot-applications/
CREATE TABLE farm
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seed_count       INTEGER                                 NOT NULL,
    fertilizer_level INTEGER                                 NOT NULL,
    CONSTRAINT pk_farm PRIMARY KEY (id)
);

CREATE TABLE player
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(255),
    farming_level    DOUBLE PRECISION                        NOT NULL,
    balance          INTEGER                                 NOT NULL,
    is_tiller        BOOLEAN                                 NOT NULL,
    is_agriculturist BOOLEAN                                 NOT NULL,
    farm_id          BIGINT,
    CONSTRAINT pk_player PRIMARY KEY (id)
);